/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Admin': RouteRecordInfo<'/Admin', '/Admin', Record<never, never>, Record<never, never>>,
    '/Contact/Index': RouteRecordInfo<'/Contact/Index', '/Contact/Index', Record<never, never>, Record<never, never>>,
    '/ExerciseDatabase': RouteRecordInfo<'/ExerciseDatabase', '/ExerciseDatabase', Record<never, never>, Record<never, never>>,
    '/Exercisepage': RouteRecordInfo<'/Exercisepage', '/Exercisepage', Record<never, never>, Record<never, never>>,
    '/Max': RouteRecordInfo<'/Max', '/Max', Record<never, never>, Record<never, never>>,
    '/Rachel': RouteRecordInfo<'/Rachel', '/Rachel', Record<never, never>, Record<never, never>>,
    '/SignUp': RouteRecordInfo<'/SignUp', '/SignUp', Record<never, never>, Record<never, never>>,
    '/Social': RouteRecordInfo<'/Social', '/Social', Record<never, never>, Record<never, never>>,
  }
}
